# Generated by Django 3.0.3 on 2020-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='aadhar_no',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='city',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='first_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='gender',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='last_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='mobile_no',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='sec_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='state',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
