# Generated by Django 3.0.3 on 2020-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200328_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='aadhar_no',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='sec_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofileinfoform',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
