# Generated by Django 3.0.3 on 2020-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_nostoppingroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostoppingroute',
            name='station1_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='nostoppingroute',
            name='station2_code',
            field=models.CharField(max_length=3),
        ),
    ]
