# Generated by Django 3.0.3 on 2020-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200328_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostoppingroute',
            name='train_no',
            field=models.IntegerField(unique=True),
        ),
    ]
