# Generated by Django 3.0.3 on 2020-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20200328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostoppingroute',
            name='route_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
