# Generated by Django 3.0.3 on 2020-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20200328_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('train_no', models.IntegerField()),
                ('origin_station_code', models.CharField(max_length=3)),
                ('dest_station_code', models.CharField(max_length=3)),
            ],
        ),
    ]
