# Generated by Django 3.0.3 on 2020-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_nostoppingroute_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostoppingroute',
            name='price',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
