# Generated by Django 3.0.3 on 2020-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_bookingdetails_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='cost',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='nostoppingroute',
            name='price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='nostoppingroute',
            name='seats',
            field=models.CharField(max_length=3),
        ),
    ]
