# Generated by Django 3.0.3 on 2020-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_auto_20200328_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='cost',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='nostoppingroute',
            name='price',
            field=models.CharField(default='250', max_length=3),
        ),
        migrations.AlterField(
            model_name='nostoppingroute',
            name='seats',
            field=models.CharField(default='200', max_length=3),
        ),
    ]
