# Generated by Django 3.0.3 on 2020-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20200328_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostoppingroute',
            name='station1_departure',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nostoppingroute',
            name='station2_arrival',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
