# Generated by Django 3.0.3 on 2020-08-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='sec_code',
        ),
        migrations.RemoveField(
            model_name='userprofileinfoform',
            name='state',
        ),
    ]
