# Generated by Django 3.0.3 on 2020-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_auto_20200809_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserOTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfoform',
            name='active',
            field=models.CharField(default=False, max_length=5),
            preserve_default=False,
        ),
    ]
