# Generated by Django 3.0.3 on 2020-08-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_auto_20200809_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
        migrations.DeleteModel(
            name='NoStoppingRoute',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
