# Generated by Django 3.0.3 on 2020-10-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0025_auto_20201017_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
