# Generated by Django 3.0.3 on 2020-10-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0027_group_groupassociation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
