# Generated by Django 3.0.3 on 2020-10-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_auto_20201027_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAssociation',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
