# Generated by Django 3.0.3 on 2020-10-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0030_groupassociation_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAssociation',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
