# Generated by Django 3.0.3 on 2020-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.CharField(max_length=100)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('package_id', models.CharField(max_length=100)),
                ('travel_type', models.CharField(max_length=100)),
                ('from_area_id', models.CharField(max_length=100)),
                ('to_area_id', models.CharField(max_length=100)),
                ('from_city_id', models.CharField(max_length=100)),
                ('to_city_id', models.CharField(max_length=100)),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('online_booking', models.CharField(max_length=100)),
                ('mobile_booking', models.CharField(max_length=100)),
                ('booking_created', models.CharField(max_length=100)),
                ('from_lat', models.CharField(max_length=100)),
                ('from_long', models.CharField(max_length=100)),
                ('to_lat', models.CharField(max_length=100)),
                ('to_long', models.CharField(max_length=100)),
                ('car_cancellation', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
    ]
