# Generated by Django 3.0.3 on 2020-10-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0034_auto_20201027_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
