# Generated by Django 3.0.3 on 2020-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0036_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Grp',
        ),
    ]
