# Generated by Django 3.0.3 on 2020-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0037_auto_20201027_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.CharField(max_length=100)),
                ('groupID', models.CharField(max_length=100)),
            ],
        ),
    ]
