# Generated by Django 3.0.3 on 2020-10-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0038_groupassociation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupassociation',
            old_name='emailID',
            new_name='username',
        ),
    ]
