# Generated by Django 3.0.3 on 2020-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0041_auto_20201116_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
